name: 'Path to Docker Image Name'
description: 'Converts a directory path to a valid docker image name'
inputs:
  path:
    description: 'The path to clean'
    required: true
  prefix:
    description: 'A prefix to remove'
    required: false
    default: ''
outputs:
  image-name:
    description: 'Valid docker image name'

branding:
  icon: 'activity'
  color: 'green'

runs:
  using: 'node16'
  main: 'index.js'


